import "./globals.css";
import { Inter } from "next/font/google";
import LayoutComponent from "@/components/LayoutComponent";
import { ReduxProvider } from "@/redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyChat Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <LayoutComponent>{children}</LayoutComponent>
        </ReduxProvider>
      </body>
    </html>
  );
}
